/**
 * form-page-registry-generator.ts — Maintains a registry file that maps
 * formKey → lazy-loaded CUSTOMER page component. This file IS regenerated
 * on every generate call (unlike the per-form files which are never overwritten).
 *
 * The registry always points to the customer layer. By default the customer
 * page re-exports the product page, so the full chain is:
 *   registry → customer/Page → src/components/forms/<key>/Page → FormPage engine
 *
 * Output: src/components/forms/registry.ts
 */
import { existsSync, readdirSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

/**
 * Scan customer/forms/ for subdirectories containing Page.tsx,
 * then write a registry file with lazy imports for each one.
 */
export function regenerateFormPageRegistry(): string[] {
  const projectRoot = process.cwd();
  const customerFormsDir = join(projectRoot, "customer", "forms");

  // Ensure output directory exists
  mkdirSync(join(projectRoot, "src", "components", "forms"), { recursive: true });

  // Find all customer form directories with a Page.tsx
  const formKeys: string[] = [];
  if (existsSync(customerFormsDir)) {
    for (const entry of readdirSync(customerFormsDir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        const pagePath = join(customerFormsDir, entry.name, "Page.tsx");
        if (existsSync(pagePath)) {
          formKeys.push(entry.name);
        }
      }
    }
  }
  formKeys.sort();

  const lines = [
    `/**`,
    ` * AUTO-GENERATED — Do not edit manually.`,
    ` * Regenerated by Entity Designer on every Generate.`,
    ` * Maps formKey → lazy-loaded customer page component.`,
    ` */`,
  ];

  if (formKeys.length > 0) {
    lines.push(`import dynamic from "next/dynamic";`);
  }
  lines.push(`import type { ComponentType } from "react";`);
  lines.push(``);
  lines.push(`interface FormPageProps {`);
  lines.push(`  activeNav: string;`);
  lines.push(`  onNavigate: (key: string, oid?: string) => void;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const formPageRegistry: Record<string, ComponentType<FormPageProps>> = {`);

  for (const key of formKeys) {
    lines.push(`  "${key}": dynamic(() => import("@customer/forms/${key}/Page")),`);
  }

  lines.push(`};`);
  lines.push(``);

  const fullPath = join(projectRoot, "src", "components", "forms", "registry.ts");
  writeFileSync(fullPath, lines.join("\n"), "utf-8");

  return formKeys;
}
