/**
 * AUTO-GENERATED — Do not edit manually.
 * Regenerated by Entity Designer on every Generate.
 * Maps formKey → lazy-loaded customer page component.
 */
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

interface FormPageProps {
  activeNav: string;
  onNavigate: (key: string, oid?: string) => void;
  selectRecordOid?: string;
  selectSeq?: number;
}

export const formPageRegistry: Record<string, ComponentType<FormPageProps>> = {
  "POReq": dynamic(() => import("@customer/forms/POReq/Page")),
  "users": dynamic(() => import("@customer/forms/users/Page")),
};
