/**
 * AUTO-GENERATED — Do not edit manually.
 * Regenerated by Entity Designer on every Generate.
 * Maps formKey → lazy-loaded customer page component.
 */
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

interface FormPageProps {
  activeNav: string;
  onNavigate: (key: string, oid?: string) => void;
}

export const formPageRegistry: Record<string, ComponentType<FormPageProps>> = {
  "POReq": dynamic(() => import("@customer/forms/POReq/Page")),
  "groups": dynamic(() => import("@customer/forms/groups/Page")),
  "locales": dynamic(() => import("@customer/forms/locales/Page")),
  "pasoe_brokers": dynamic(() => import("@customer/forms/pasoe_brokers/Page")),
  "users": dynamic(() => import("@customer/forms/users/Page")),
};
